### PR TITLE
timeseries-connector_embed-video

### PR DESCRIPTION
**Pull request by joyrostie**

### CODE REVIEW

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-29.javascript-getting-started.preview.cogniteapp.com

**Comment by f1cognite** [comment]
@joyrostie Can we make it more obvious that the user can click on it to play? Also it is maybe a bit too big?

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-29.javascript-getting-started.preview.cogniteapp.com

**Comment by joyrostie** [comment]
@f1cognite please check main readme at 
https://github.com/cognitedata/javascript-getting-started/tree/embed_video 
Timeseries Connector app guide picture changed to smaller one.

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-29.javascript-getting-started.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-29.javascript-getting-started.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-29.javascript-getting-started.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-29.javascript-getting-started.preview.cogniteapp.com

**Pull request merged**
