### PR TITLE
docs(readme): link to SDK video intro guide

### PR DESCRIPTION
**Pull request by polomani**

### CODE REVIEW

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-48.javascript-getting-started.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-48.javascript-getting-started.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-48.javascript-getting-started.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This apps can now be previewed at the following URL: https://pr-48.javascript-getting-started.preview.cogniteapp.com

**Comment by f1cognite** [comment]
Worth adding this to the cognitesdk-js README as well?

**Comment by polomani** [comment]
yes

**Pull request merged**
